import Head from 'next/head'
import Image from 'next/image'
import Nav from '../src/nav'
import About from '../src/About'
import { Box, Flex, Space, Center } from '@chakra-ui/react'
import { motion } from "framer-motion"

export default function Home() {

  const variants = {
    hidden: {scale: 0.5},
    visible: {scale: 1},
  }

  const MotionBox = motion(Box)

  return (
    <MotionBox initial="hidden" animate="visible" variants={variants} bg="brand.primary">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="space-evenly">
        <Center height="100vh" flexBasis="60%"><About/></Center>
        <Center flexBasis="40%"><Nav/></Center>
      </Flex>
    </MotionBox>
  )
}
