import Head from 'next/head'
import Image from 'next/image'
import Nav from '../src/nav'
import About from '../src/About'
import { Box, Flex, Space, Center } from '@chakra-ui/react'
import { motion } from "framer-motion"

export default function Home() {

  const variants = {
    hidden: {y: -200, opacity: 0, },
    visible: {y: 0, opacity: 1, },
    transition: "ease",
  }

  const MotionBox = motion(Box)

  return (
    <MotionBox initial="hidden" animate="visible" variants={variants} bg="brand.primary">
      <Head>
        <title>Juan Ciudad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection={{base: "column", md: "row", lg: "row"}}>
        <Center flexBasis={{base: "0%", md: "60%", lg: "60%"}}><About/></Center>
        <Center flexBasis={{base: "0%", md: "40%", lg: "40%"}}><Nav/></Center>
      </Flex>
    </MotionBox>
  )
}
